#Prosty Makefile

#Obiekt "programMain" zalezny jest od plikow dwaPlikiC.o i mainDwaPlikiC.o

CC=g++
OBJS=dwaPlikiC.o mainDwaPlikiC.o

mainDwaPlikiC: $(OBJS)
	$(CC) $^ -o $@

mainDwaPlikiC.o: mainDwaPlikiC.cc
	$(CC) -c $< -o $@

dwaPlikiC.o: dwaPlikiC.cc
	$(CC) -c $< -o $@

clean:
	rm -f *.o mainDwaPlikiC
